core/accounts/api/v1/urls.py
from django.urls import path
from rest_framework import routers
from rest_framework.authtoken.views import ObtainAuthToken
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

from . import views


app_name = "api-v1"


router = routers.DefaultRouter()
router.register("profile", views.ProfileViewSet, basename="profile")

urlpatterns = [
    # دوباره فرستادن ایمیل به کاربر
    path("verify/resend/", views.VerificationEmail.as_view(), name="email_resend"),
    # احراز هویت
    path("verify-email/", views.VerificationEmail.as_view(), name="email_verify"),
    path(
        "verify/confirm/<str:token>/",
        views.UserVerificationViewSet.as_view(),
        name="user_verify",
    ),
    
    # jwt
    path("jwt/create/", views.CustomTokenObtainPairView.as_view(), name="jwt_create"),
    path("jwt/refresh/", TokenRefreshView.as_view(), name="jwt_refresh"),
    path("jwt/verify/", TokenVerifyView.as_view(), name="jwt_verify"),
    path(
        "change-password/",
        views.ChangePasswordAPIView.as_view(),
        name="change_password",
    ),
    # Token
    path("token/login/", ObtainAuthToken.as_view(), name="token_login"),
    path("token/logout/", views.CustomDiscardAuthToken.as_view(), name="token_logout"),

]

urlpatterns += router.urls

core/accounts/urls.py
from django.urls import path, include
from .views import CustomLoginView, RegisterPage
from django.contrib.auth.views import LogoutView

app_name = "accounts"

urlpatterns = [
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(next_page="/"), name="logout"),
    path("register/", RegisterPage.as_view(), name="register"),
    path("", include("django.contrib.auth.urls")),
    path("api/v1/", include("accounts.api.v1.urls")),
]

core/blog/urls.py
from django.urls import path, include
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.index, name="index"),
    # api 🙂
    path("api/v1/", include("blog.api.v1.urls")),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls")),
    path("accounts/", include("accounts.urls")),
    path("comment/", include("comment.urls")),
    
        # Documenting API
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI:
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    # login for drf
    path("api-auth/", include("rest_framework.urls")),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/accounts/models/profile.py
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.db import models
from .user import MyUser


class Profile(models.Model):
    user = models.ForeignKey(
        "accounts.MyUser", on_delete=models.CASCADE, related_name="profile"
    )
    first_name = models.CharField(max_length=250)
    last_name = models.CharField(max_length=250)
    image = models.ImageField(blank=True, null=True, upload_to="profile/")
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.user.email


@receiver(post_save, sender=MyUser)
def create_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

core/accounts/models/user.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser, PermissionsMixin
)

class MyUserManager(BaseUserManager):
    def create_user(self,email,password,**extra_fields):
        """
        Creates and saves a User with (email, password)
        """
        if not email:
            raise ValueError("the Email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user
    
    def create_superuser(self,email,password,**extra_fields):
        """
        Creates a superuser with (email, password)
        """
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("is_active", True)
        
        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")
        
        return self.create_user(email, password, **extra_fields) 

    
    
class MyUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(max_length=255, unique=True)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []
    objects = MyUserManager()
    
    def __str__(self):
        return self.email

core/accounts/forms.py
from typing import Any
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, get_user_model
from django.core.exceptions import ValidationError
UserModel = get_user_model()
from .models import MyUser

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = MyUser
        fields = ("email",)
    
    def save(self, commit: bool = ...) -> Any:
        user = super().save(commit)
        # user.fullname = self.cleaned_data["fullname"]
        user.is_active = True
        if commit:
            user.save()
        return user
    

class CustomAuthenticationForm(forms.Form):
    """
    Base class for authenticating users. Extend this to get a form that accepts
    email/password logins.
    """

    email = forms.EmailField(
        label='Email',
        widget=forms.TextInput(
            attrs = {
                'placeholder': 'email',
                "autofocus": True
            }
        )
    )
    password = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "current-password"}),
    )

    error_messages = {
        "invalid_login": 
            "Please enter a correct email and password. Note that both "
            "fields may be case-sensitive."
        ,
        "inactive": "This account is inactive.",
    }

    def __init__(self, request=None, *args, **kwargs):
        """
        The 'request' parameter is set for custom auth use by subclasses.
        The form data comes in via the standard 'data' kwarg.
        """
        self.request = request
        self.user_cache = None
        super().__init__(*args, **kwargs)


    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")

        if email is not None and password:
            self.user_cache = authenticate(
                self.request, username=email, password=password
            )
            if self.user_cache is None:
                raise self.get_invalid_login_error()
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data

    def confirm_login_allowed(self, user):
        """
        Controls whether the given User may log in. This is a policy setting,
        independent of end-user authentication. This default behavior is to
        allow login by active users, and reject login by inactive users.

        If the given user cannot log in, this method should raise a
        ``ValidationError``.

        If the given user may log in, this method should return None.
        """
        if not user.is_active:
            raise ValidationError(
                self.error_messages["inactive"],
                code="inactive",
            )

    def get_user(self):
        return self.user_cache

    def get_invalid_login_error(self):
        return ValidationError(
            self.error_messages["invalid_login"],
            code="invalid_login",
        )

# ! not work because username field is required
# class LoginForm(AuthenticationForm):
#     email = forms.EmailField(
#         label='Email',
#         widget=forms.TextInput(
#             attrs = {
#                 'placeholder': 'email',
#                 "autofocus": True
#             }
#         )
#     )
    
#     def clean(self):
#         print("******************")
#         self.fields["username"].required = False
#         print(self.fields["username"].__dict__)
#         print("____________________")
#         print(self.fields["email"].__dict__)
#         print("hello")
#         username = self.cleaned_data.get("email")
#         password = self.cleaned_data.get("password")
#         print("cleaned data:", self.cleaned_data)
#         print("username is ",username)
#         if username is not None and password:
#             self.user_cache = authenticate(
#                 self.request, username=username, password=password
#             )
#             print("user_cashe:",self.user_cache)
#             if self.user_cache is None:
#                 raise self.get_invalid_login_error()
#             else:
#                 self.confirm_login_allowed(self.user_cache)

#         return self.cleaned_data

#     def confirm_login_allowed(self, user: AbstractBaseUser) -> None:
#         print(user.__dict__)
#         return super().confirm_login_allowed(user)
    

#     # password = forms.CharField(
#     #     label='Password', 
#     #     widget=forms.PasswordInput(
#     #         attrs = {
#     #             'placeholder': 'password'
#     #         }
#     #     )
#     # )
    

core/accounts/api/v1/views.py
from rest_framework.viewsets import ModelViewSet
from rest_framework import generics, status
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from rest_framework.parsers import MultiPartParser, FormParser
from rest_framework_simplejwt.views import TokenObtainPairView
from rest_framework_simplejwt.tokens import RefreshToken
from rest_framework.throttling import ScopedRateThrottle
from django.contrib.auth import get_user_model
from django.core.mail import send_mail
from django.conf import settings
import jwt


from .serializers import (
    ProfileSerializer,
    CustomTokenObtainPairSerializer,
    ChangePasswordSerializer,
)
from accounts.models.profile import Profile
from accounts.models.user import MyUser
from .permissions import IsOwnerOrReadOnly


User = get_user_model()

# قابلیت تغییر و اضافه کردن و مشاهده کردن پروفایل کاربر
class ProfileViewSet(ModelViewSet):
    serializer_class = ProfileSerializer
    permission_classes = [
        IsOwnerOrReadOnly,
    ]
    queryset = Profile.objects.all()
    http_method_names = ("get", "post", "put", "patch", "head")


# خروجی شخصی سازی شده بدون اینکه صرفا توکن به کاربر برگرده
class CustomTokenObtainPairView(TokenObtainPairView):
    serializer_class = CustomTokenObtainPairSerializer

# حذف توکن کاربر
class CustomDiscardAuthToken(APIView):
    permission_classes = [IsAuthenticated,]

    def post(self, request):
        request.user.auth_token.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


# تغییر پسورد کاربر
class ChangePasswordAPIView(generics.UpdateAPIView):
    model = User
    permission_classes = [
        IsAuthenticated,
    ]
    serializer_class = ChangePasswordSerializer

    def get_object(self, queryset=None):
        obj = self.request.user
        return obj

    def put(self, request, *args, **kwargs):
        self.object = self.get_object()
        # دو کد زیر مشابه همدیگه هستند
        # serializer = self.get_serializer(data=request.data)
        serializer = ChangePasswordSerializer(data=request.data)
        if serializer.is_valid():
            # بررسی پسورد وارد شده
            if not self.object.check_password(serializer.data.get("old_password")):
                return Response({"old_password": "wrong password!"}, status=status.HTTP_400_BAD_REQUEST)
            self.object.set_password(serializer.data.get("new_password"))
            self.object.save()
            return Response({"detail": "password changed"},status=status.HTTP_200_OK)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

# فعال کردن حساب کاربری با ایمیل 😎✌
class VerificationEmail(generics.GenericAPIView):
    throttle_scope = "email"
    permission_classes = [IsAuthenticated,]

    def get(self, request, *args, **kwargs):
        # اول بررسی کنیم کاربر از قبل احراز هویت نشده باشد
        if request.user.is_verified:
            return Response(
                {"detail": "your account is already verified"},
                status=status.HTTP_400_BAD_REQUEST,
            )
        self.user_obj = self.request.user
        tokens = self.get_tokens_for_user(self.user_obj)
        # ! ست کردیم مطابقت داشته باشد urls.py با اونی که داخل url  دقت کنید که باید 
        # ! درخواست ارسال کند UserVerificationViewSet زیر قراره به کلاس url در حقیقت
        mail_txt = f"verify your account:\n\n \
            http://localhost:8000/accounts/api/v1/verify/confirm/{tokens['access']}/"

        send_mail(
            "ایمیل احراز هویت",
            mail_txt,
            "from@example.com",
            [self.user_obj.email],
            fail_silently=False,
        )
        return Response(f"email sent {request.method}")

    # ساخت توکن جدید در صورت نیاز
    def get_tokens_for_user(self, user):
        refresh = RefreshToken.for_user(user)

        return {
            "access": str(refresh.access_token),
            "refresh": str(refresh),
        }

# کنیم verified کلیک کرد با کمک کلاس زیر سعی می کنیم کاربر را url بعد که کاربر روی اون
class UserVerificationViewSet(APIView):

    def get(self, request, token, *args, **kwargs):
        try:
            token = jwt.decode(token, settings.SECRET_KEY, algorithms=["HS256"])
        except jwt.exceptions.ExpiredSignatureError:
            return Response(
                {"detail": "token expired!"}, status=status.HTTP_400_BAD_REQUEST
            )
        except jwt.exceptions.InvalidSignatureError:
            return Response(
                {"detail": "signature is invalid"}, status=status.HTTP_400_BAD_REQUEST
            )

        user = User.objects.get(id=token["user_id"])
        if user.is_verified:
            return Response({"detail": "user is already verified."})
        user.is_verified = True
        user.save()
        return Response(
            {"detail": "user account verification completed"},
            status=status.HTTP_202_ACCEPTED,
        )

core/accounts/views.py
from django.contrib.auth.views import LoginView
from django.views.generic.edit import FormView
from django.urls import reverse_lazy
from django.contrib.auth import login
from django.shortcuts import redirect
from .forms import CustomAuthenticationForm, CustomUserCreationForm
from django.contrib.auth import login, logout
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect


class CustomLoginView(LoginView):
    template_name = "accounts/login.html"
    redirect_authenticated_user = True # remeber this warning https://docs.djangoproject.com/en/4.2/topics/auth/default/#django.contrib.auth.views.LoginView.redirect_authenticated_user
    form_class = CustomAuthenticationForm
    success_url = reverse_lazy('blog:index')

    def get_success_url(self):
        return reverse_lazy("blog:index")
    

class RegisterPage(FormView):
    template_name = "accounts/register.html"
    form_class = CustomUserCreationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy("blog:index")

    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request, user)
        return super(RegisterPage, self).form_valid(form)

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect("blog:index")
        return super(RegisterPage, self).get(*args, **kwargs)

def Logout(request):
    """logout logged in user"""
    logout(request)
    return HttpResponseRedirect(reverse_lazy('custom_auth:dashboard'))

core/accounts/templates/accounts/login.html
{% extends 'base.html' %} {% block content %}
<div class="login-wrap">
    <div class="login-html">
        <div id="tab-1" type="radio" name="tab" class="sign-in" checked>
            <label for="tab-1" class="tab">Login</label>
        </div>
        {% comment %}
        <div id="tab-2" type="radio" name="tab" class="sign-up">
            <label for="tab-2" class="tab">Sign Up</label>
        </div>
        {% endcomment %}
        <form class="login-form" action="{% url 'accounts:login' %}" method="POST">
            {% comment %}! لاگین{% endcomment %}
            <div class="sign-in-htm">
                {% csrf_token %}

                {% comment %} <table>
                    <tr>
                        <td>{{ form.email.label_tag }}</td>
                        <td>{{ form.email }}</td>
                    </tr>
                    <tr>
                        <td>{{ form.password.label_tag }}</td>
                        <td>{{ form.password }}</td>
                    </tr>
                </table> {% endcomment %}

                <div class="group">
                    <label for="email" class="label">Email</label>
                    <input id="email" name="email" type="email" class="input" />
                </div>
                <div class="group">
                    <label for="pass" class="label">Password</label>
                    <input id="password" name="password" type="password" class="input" data-type="password" />
                </div>

                {% comment %}
                <div class="group">
                    <input id="check" type="checkbox" class="check" checked />
                    <label for="check"><span class="icon"></span> Keep me Signed in</label>
                </div>
                {% endcomment %}
                <div class="group">
                    <button type="submit" class="button" value="Sign In">Sign In</button>
                </div>
                <div class="hr"></div>
                <div class="foot-lnk">
                    <a href="{% url 'accounts:register' %}">Want to Sign-Up?</a>
                </div>
            </div>
        </form>
        {% if form.errors %}
        <div class="alert alert-error">
            <h6>Please fix the following errors</h6>
            <ul>
                {% for field in form %}
                {% if field.errors %}
                {% for error in field.errors %}
                <li>
                    <a href="#id_{{ field.name }}" class="error">{{ error|escape }}</a>
                </li>
                {% endfor %}
                {% endif %}
                {% endfor %}
            </ul>
            {% if form.non_field_errors %} {{ form.non_field_errors }} {% endif %}
        </div>
        {% endif %}
        
{% comment %} 
        {% if messages %}
        {% for message in messages %}
            {{ message|safe }}
        {% endfor %}
        {% endif %}

        {% if form.errors %}
        <div class="alert alert-error">
            <ul>
                {% for field in form %}
                {% if field.errors %}
                {% for error in field.errors %}
                    {{ error|escape }}
                {% endfor %}
                {% endif %}
                {% endfor %}
            </ul>
            {% if form.non_field_errors %}
                {{ form.non_field_errors.as_text }}
            {% endif %}
        </div>
        {% endif %} {% endcomment %}
    </div>
</div>
{% endblock %}

core/accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="login-wrap registeringwrap" style="background-image: url('{% static 'images/bg.jpg' %}');">
        <div class="login-html">
            {% comment %} <div id="tab-1" type="radio" name="tab" class="sign-in" checked><label for="tab-1" class="tab">Login</label></div> {% endcomment %}
            <div id="tab-2" type="radio" name="tab" class="sign-up"><label for="tab-2" class="tab">Sign Up</label></div>
            <form class="login-form" action="{% url 'accounts:register' %}" method="post">
                {% comment %}! ثبت نام  {% endcomment %}
                <div class="sign-up-htm" >
                    {% csrf_token %}
                    {% comment %} {{form.as_p}} {% endcomment %}
                    <div class="group">
                        <label class="label">Email Address</label>
                        <input id="email" name="email" type="email" class="input">
                    </div>
                    <div class="group">
                        <label class="label">Password</label>
                        <input id="password1" name="password1" type="password"  class="input" data-type="password">
                    </div>
                    <div class="group">
                        <label for="pass" class="label">Repeat Password</label>
                        <input id="password2" name="password2" type="password" class="input" data-type="password">
                    </div>
                    <div class="group">
                        <input type="submit" class="button" value="Sign Up">
                    </div>
                    <div class="hr" style=""></div>
                    <div class="foot-lnk">
                        <a href="{% url 'accounts:login' %}">Already Member?</a>
                    </div>
                </div>
            </form>
            {% if form.errors %}
            <div class="alert alert-error" style="margin-top: 25px;">
                <h6>Please fix the following errors</h6>
                <ul>
                    {% for field in form %}
                    {% if field.errors %}
                    {% for error in field.errors %}
                    <li>
                        <a href="#id_{{ field.name }}" class="error">{{ error|escape }}</a>
                    </li>
                    {% endfor %}
                    {% endif %}
                    {% endfor %}
                </ul>
                {% if form.non_field_errors %} {{ form.non_field_errors }} {% endif %}
            </div>
            {% endif %}
        </div>
    </div>
{% endblock %}